export const GbcLicensees = {
	'00':	'none'
	, '01':	'nintendo'
	, '08':	'capcom'
	, '13':	'electronic arts'
	, '18':	'hudsonsoft'
	, '19':	'b-ai'
	, '20':	'kss'
	, '22':	'pow'
	, '24':	'pcm complete'
	, '25':	'san-x'
	, '28':	'kemco japan'
	, '29':	'seta'
	, '30':	'viacom'
	, '31':	'nintendo'
	, '32':	'bandia'
	, '33':	'ocean/acclaim'
	, '34':	'konami'
	, '35':	'hector'
	, '37':	'taito'
	, '38':	'hudson'
	, '39':	'banpresto'
	, '41':	'ubi soft'
	, '42':	'atlus'
	, '44':	'malibu'
	, '46':	'angel'
	, '47':	'pullet-proof'
	, '49':	'irem'
	, '50':	'absolute'
	, '51':	'acclaim'
	, '52':	'activision'
	, '53':	'american sammy'
	, '54':	'konami'
	, '55':	'hi tech entertainment'
	, '56':	'ljn'
	, '57':	'matchbox'
	, '58':	'mattel'
	, '59':	'milton bradley'
	, '60':	'titus'
	, '61':	'virgin'
	, '64':	'lucasarts'
	, '67':	'ocean'
	, '69':	'electronic arts'
	, '70':	'infogrames'
	, '71':	'interplay'
	, '72':	'broderbund'
	, '73':	'sculptured'
	, '75':	'sci'
	, '78':	't*hq'
	, '79':	'accolade'
	, '80':	'misawa'
	, '83':	'lozc'
	, '86':	'tokuma shoten i*'
	, '87':	'tsukuda ori*'
	, '91':	'chun soft'
	, '92':	'video system'
	, '93':	'ocean/acclaim'
	, '95':	'varie'
	, '96':	'yonezawa/s\'pal'
	, '97':	'kaneko'
	, '99':	'pack in soft'
};
