export const Licensees = {
	'00':   'none'
	, '01': 'nintendo'
	, '08': 'capcom'
	, '09': 'hot-b'
	, '0A': 'jaleco'
	, '0B': 'coconuts'
	, '0C': 'elite systems'
	, '13': 'electronic arts'
	, '18': 'hudsonsoft'
	, '19': 'itc entertainment'
	, '1A': 'yanoman'
	, '1D': 'clary'
	, '1F': 'virgin'
	, '20': 'KSS'
	, '24': 'pcm complete'
	, '25': 'san-x'
	, '28': 'kotobuki systems'
	, '29': 'seta'
	, '30': 'infogrames'
	, '31': 'nintendo'
	, '32': 'bandai'
	, '33': 'GBC - see above'
	, '34': 'konami'
	, '35': 'hector'
	, '38': 'Capcom'
	, '39': 'Banpresto'
	, '3C': '*entertainment i'
	, '3E': 'gremlin'
	, '41': 'Ubisoft'
	, '42': 'Atlus'
	, '44': 'Malibu'
	, '46': 'angel'
	, '47': 'spectrum holoby'
	, '49': 'irem'
	, '4A': 'virgin'
	, '4D': 'malibu'
	, '4F': 'u.s. gold'
	, '50': 'absolute'
	, '51': 'acclaim'
	, '52': 'activision'
	, '53': 'american sammy'
	, '54': 'gametek'
	, '55': 'park place'
	, '56': 'ljn'
	, '57': 'matchbox'
	, '59': 'milton bradley'
	, '5A': 'mindscape'
	, '5B': 'romstar'
	, '5C': 'naxat soft'
	, '5D': 'tradewest'
	, '60': 'titus'
	, '61': 'virgin'
	, '67': 'ocean'
	, '69': 'electronic arts'
	, '6E': 'elite systems'
	, '6F': 'electro brain'
	, '70': 'Infogrammes'
	, '71': 'Interplay'
	, '72': 'broderbund'
	, '73': 'sculptered soft'
	, '75': 'the sales curve'
	, '78': 't*hq'
	, '79': 'accolade'
	, '7A': 'triffix entertainment'
	, '7C': 'microprose'
	, '7F': 'kemco'
	, '80': 'misawa entertainment'
	, '83': 'lozc'
	, '86': 'tokuma shoten intermedia'
	, '8B': 'bullet-proof software'
	, '8C': 'vic tokai'
	, '8E': 'ape'
	, '8F': 'i\'max'
	, '91': 'chun soft'
	, '92': 'video system'
	, '93': 'tsuburava'
	, '95': 'varie'
	, '96': 'yonezawa/s\'pal'
	, '97': 'kaneko'
	, '99': 'arc'
	, '9A': 'nihon bussan'
	, '9B': 'Tecmo'
	, '9C': 'imagineer'
	, '9D': 'Banpresto'
	, '9F': 'nova'
	, 'A1': 'Hori electric'
	, 'A2': 'Bandai'
	, 'A4': 'Konami'
	, 'A6': 'kawada'
	, 'A7': 'takara'
	, 'A9': 'technos japan'
	, 'AA': 'broderbund'
	, 'AC': 'Toei animation'
	, 'AD': 'toho'
	, 'AF': 'Namco'
	, 'B0': 'Acclaim'
	, 'B1': 'ascii or nexoft'
	, 'B2': 'Bandai'
	, 'B4': 'Enix'
	, 'B6': 'HAL'
	, 'B7': 'SNK'
	, 'B9': 'pony canyon'
	, 'BA': '*culture brain o'
	, 'BB': 'Sunsoft'
	, 'BD': 'Sony imagesoft'
	, 'BF': 'sammy'
	, 'C0': 'Taito'
	, 'C2': 'Kemco'
	, 'C3': 'Squaresoft'
	, 'C4': 'tokuma shoten intermedia'
	, 'C5': 'data east'
	, 'C6': 'tonkin house'
	, 'C8': 'koei'
	, 'C9': 'ufl'
	, 'CA': 'ultra'
	, 'CB': 'vap'
	, 'CC': 'use'
	, 'CD': 'meldac'
	, 'CE': '*pony canyon or'
	, 'CF': 'angel'
	, 'D0': 'Taito'
	, 'D1': 'sofel'
	, 'D2': 'quest'
	, 'D3': 'sigma enterprises'
	, 'D4': 'ask kodansha'
	, 'D6': 'naxat soft'
	, 'D7': 'copya systems'
	, 'D9': 'Banpresto'
	, 'DA': 'tomy'
	, 'DB': 'ljn'
	, 'DD': 'ncs'
	, 'DE': 'human'
	, 'DF': 'altron'
	, 'E0': 'jaleco'
	, 'E1': 'towachiki'
	, 'E2': 'uutaka'
	, 'E3': 'varie'
	, 'E5': 'epoch'
	, 'E7': 'athena'
	, 'E8': 'asmik'
	, 'E9': 'natsume'
	, 'EA': 'king records'
	, 'EB': 'atlus'
	, 'EC': 'Epic/Sony records'
	, 'EE': 'igs'
	, 'F0': 'a wave'
	, 'F3': 'extreme entertainment'
	, 'FF': 'ljn'
};
